# Generated by Django 6.1.1 on 2026-09-20 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_name', models.CharField(max_length=120)),
                ('specialty', models.CharField(max_length=120)),
                ('clinic_name', models.CharField(max_length=160)),
                ('clinic_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('next_available', models.CharField(max_length=120)),
                ('source', models.CharField(default='demo_provider_directory', max_length=40)),
                ('is_demo', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
