# Generated by Django 6.1.1 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('symptoms', '0001_eyescan')]

    operations = [
        migrations.AddField(model_name='eyescan', name='blink_count', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='eyescan', name='blink_rate', field=models.FloatField(default=0)),
        migrations.AddField(model_name='eyescan', name='duration_seconds', field=models.PositiveIntegerField(default=60)),
        migrations.AddField(model_name='eyescan', name='recording_public_id', field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name='eyescan', name='recording_url', field=models.URLField(blank=True, max_length=500)),
        migrations.AddField(model_name='eyescan', name='redness_score', field=models.FloatField(default=0)),
        migrations.AddField(model_name='eyescan', name='tracking_quality', field=models.PositiveIntegerField(default=0)),
    ]
