# Generated by Django 6.1.1 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('symptoms', '0002_eyescan_recording_metrics')]

    operations = [
        migrations.AddField(
            model_name='eyescan',
            name='sampled_frames',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
